#!/bin/bash

#SBATCH --job-name=get_fits

# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1


# Memory usage (MB)
#SBATCH --mem=10G

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=03:00:00

#SBATCH --mail-user=csmi0005@student.monash.edu
#SBATCH --mail-type=FAIL

# Command to run a gpu job
source ~/.bashrc
cd /mnt/lustre/projects/Mona0028/adonea/cameron
conda activate ./envs/main
cd Honours
time python retrieve_fits.py